services:
  frontend:
    image: frontend:prod
    container_name: frontend-prod-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
  
  backend:
    image: backend:prod
    container_name: backend-prod-container
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./backend/src/WebApi/wwwroot/images:/app/wwwroot/images
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
  
  redis:
    image: redis:7-alpine
    container_name: redis-prod-container
    restart: always
    command:
      - redis-server
      - --requirepass "redispass"
      - --maxmemory "512mb"
      - --maxmemory-policy allkeys-lru
      - --save ""
      - --appendonly no
    env_file:
      - ./backend/.env
    deploy:
      resources:
        limits:
          memory: 600M
  
  db:
    image: postgis/postgis:17-3.5-alpine
    container_name: db-prod-container
    restart: always
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env