services:
  frontend:
    image: frontend:dev
    container_name: frontend-dev-container
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
      - "9222:9222"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
  
  backend:
    image: backend:dev
    container_name: backend-dev-container
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/src/WebApi/wwwroot/images:/src/WebApi/wwwroot/images
    env_file:
      - ./backend/.env
    depends_on:
      - db
  
  redis:
    image: redis:7-alpine
    container_name: redis-dev-container
    restart: always
    command:
      - redis-server
      - --requirepass "redispass"
      - --maxmemory "512mb"
      - --maxmemory-policy allkeys-lru
      - --save ""
      - --appendonly no
    env_file:
      - ./backend/.env
    deploy:
      resources:
        limits:
          memory: 600M
    ports:
      - "6379:6379"
  
  db:
    image: postgis/postgis:17-3.5-alpine
    container_name: db-dev-container
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env