services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm-proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:81:81'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - shared_net
  
  frontend:
    image: frontend:prod
    container_name: frontend-prod-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - shared_net
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - django_shared_static:/staticfiles:ro
      - django_shared_media:/django/media:ro
    depends_on:
      - backend

  backend:
    image: backend:prod
    container_name: backend-prod-container
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./backend/src/WebApi/wwwroot/images:/app/wwwroot/images
    networks:
      - shared_net
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgis/postgis:17-3.5-alpine
    container_name: db-prod-container
    restart: always
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    networks:
      - shared_net

networks:
  shared_net:
    external: true
    name: shared_network

volumes:
  django_shared_media:
    external: true
  django_shared_static:
    external: true