services:
  frontend:
    image: frontend:prod
    container_name: frontend-prod-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "8001:80"
      - "443:443"
    depends_on:
      - backend
  backend:
    image: backend:prod
    container_name: backend-prod-container
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./backend/src/WebApi/wwwroot/images:/app/wwwroot/images
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    image: postgis/postgis:17-3.5-alpine
    container_name: db-prod-container
    restart: always
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env